WebTester/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('captcha/', include('captcha.urls'))
]

main/urls.py
from django.urls import path
from .views import index, test_list, test_page, LoginController, LogoutController, register_user, statistic_page, \
    find_page, api_controller, account, edit_account, PasswordChangeController

app_name = 'main'

urlpatterns = [
    path('<int:test_group_id>/<int:test_id>/', test_page, name='test_page'),
    path('<int:test_group_id>/', test_list, name='test_list'),
    path('logout/', LogoutController.as_view(), name='logout'),
    path('login/', LoginController.as_view(), name='login'),
    path('register/', register_user, name='register_user'),
    path('user_statistic/', statistic_page, name='statistic_page'),
    path('find/', find_page, name='find'),
    path('account/', account, name='account'),
    path('edit_account/', edit_account, name='edit_account'),
    path('change_password/', PasswordChangeController.as_view(), name='change_password'),
    path('api/', api_controller),
    path('', index, name='index')
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Группа тестов
class TestGroup(models.Model):
    title = models.CharField(max_length=200, unique=True, null=False, blank=False, verbose_name='Группа тестов')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа тестов'
        verbose_name_plural = 'Группы тестов'
        ordering = ['title']


# Тест
class Test(models.Model):
    title = models.CharField(max_length=200, unique=True, null=False, blank=False, verbose_name='Название теста')
    test_group = models.ForeignKey(TestGroup, on_delete=models.CASCADE, null=False, blank=False,
                                   verbose_name='Группа тестов')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'
        ordering = ['title']


# Вопрос теста
class Question(models.Model):
    title = models.CharField(max_length=1000, null=False, blank=False, verbose_name='Вопрос')
    test = models.ForeignKey(Test, on_delete=models.CASCADE, null=False, blank=False, verbose_name='Название теста')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'
        ordering = ['title']


# Вариант ответа
class Answer(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name='Вариант ответа')
    is_correct = models.BooleanField(null=False, blank=False, default=False, verbose_name='Верный ответ')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=False, blank=False, verbose_name='Вопрос')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вариант ответа'
        verbose_name_plural = 'Варианты ответа'
        ordering = ['title']


# Результат прохождения теста
class TestResult(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, verbose_name='Пользователь')
    test = models.ForeignKey(Test, on_delete=models.CASCADE, null=False, blank=False, verbose_name='Тест')
    date_test = models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения теста')
    correct_count = models.IntegerField(null=False, blank=False, verbose_name='Количество правильных ответов')
    incorrect_count = models.IntegerField(null=False, blank=False, verbose_name='Количество неправильных ответов')

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from captcha.fields import CaptchaField


# Форма для регистрации нового пользователя
class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(strip=True, label='Имя')
    last_name = forms.CharField(strip=True, label='Фамилия')
    email = forms.EmailField(label='Адрес электронной почты')
    captcha = CaptchaField(label='Введите текст с картинки')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2', 'email')
        labels = {'username': 'Логин'}

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.save()


# Форма для редактирования данных пользователя
class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(strip=True, label='Имя')
    last_name = forms.CharField(strip=True, label='Фамилия')
    email = forms.EmailField(label='Адрес электронной почты')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        labels = {'username': 'Логин'}

main/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from .models import TestGroup, Test, Question, Answer, TestResult
from .forms import UserRegisterForm, UserEditForm


# Контроллер главной страницы
def index(request):
    test_groups = TestGroup.objects.all()
    context = {'test_groups': test_groups}
    return render(request, 'main/index.html', context)


# Контроллер страницы со списком тестов
def test_list(request, test_group_id):
    selected_group = TestGroup.objects.get(pk=test_group_id)
    tests = Test.objects.filter(test_group=selected_group)
    context = {'tests': tests, 'selected_group': selected_group}
    return render(request, 'main/test_list.html', context)


# Страница теста
@login_required(login_url=reverse_lazy('main:login'))
def test_page(request, test_group_id, test_id):
    if request.method == 'GET':
        # Получаем выбранную группу и выбранный тест и добавляем их в контекст
        # Если получить информацию не удалось, то переводим пользователя на страницу с соответствующим сообщением
        try:
            selected_group = TestGroup.objects.get(pk=test_group_id)
            selected_test = Test.objects.get(pk=test_id)
            context = {'selected_group': selected_group, 'selected_test': selected_test}
        except (TestGroup.DoesNotExist, Test.DoesNotExist):
            return render(request, 'main/test_not_found_page.html', {})

        # Получаем список вопросов и добавляем их в контекст
        def get_type_for_aswers_set(answers_set):
            count_correct_answer = 0
            for answer in answers_set:
                if answer.is_correct:
                    count_correct_answer += 1
            if count_correct_answer == 1:
                return 'single_type'
            else:
                return 'multiple_type'

        questions = []
        for question in Question.objects.filter(test=selected_test):
            block = {'title': question, 'answers': []}
            answers = Answer.objects.filter(question=question)
            type_for_answers = get_type_for_aswers_set(answers)
            postfix = 0
            for answer in answers:
                if type_for_answers == 'multiple_type':
                    block['answers'].append(
                        '<input type="checkbox" name="' + str(question.pk) + '_' + str(postfix) + '" value="' + str(
                            answer.pk) + '">' + answer.title)
                    postfix += 1
                if type_for_answers == 'single_type':
                    block['answers'].append(
                        '<input type="radio" name="' + str(question.pk) + '" value="' + str(
                            answer.pk) + '">' + answer.title)
            questions.append(block)
        context['questions'] = questions

        return render(request, 'main/test_page.html', context)
    if request.method == 'POST':
        # Формируем словарь с ответами пользователя
        user_answers = {}

        for param in request.POST:
            if not param.startswith('csrf'):
                question_id = param.split('_')[0]
                if question_id not in user_answers:
                    user_answers[question_id] = []
                user_answers[question_id].append(request.POST[param])

        # Формируем словарь с правильными ответами
        correct_answers = {}
        selected_test = Test.objects.get(pk=test_id)
        questions = Question.objects.filter(test=selected_test)

        for question in questions:
            answers = Answer.objects.filter(question=question)
            for answer in answers:
                if answer.is_correct:
                    if str(question.pk) not in correct_answers:
                        correct_answers[str(question.pk)] = []
                    correct_answers[str(question.pk)].append(str(answer.pk))

        # Если пользователь ответил не на все вопросы - переводим ему на страницу с соответствующим сообщением
        if len(user_answers) != len(correct_answers):
            return render(request, 'main/invalid_answer_count.html',
                          {'test_group_id': test_group_id, 'test_id': test_id})

        # Сверяем ответы
        # Количество неправильных ответов
        incorrect_answer_count = 0
        correct_answer_count = 0
        # Список вопросов, на которые были даны неверные ответы
        incorrect_questions_list = []
        for question_id in correct_answers:
            if correct_answers[question_id] == user_answers[question_id]:
                correct_answer_count += 1
            else:
                incorrect_answer_count += 1
                incorrect_questions_list.append(Question.objects.get(pk=question_id))

        # Добавляем результат пользователя в его статистику
        test_result = TestResult()
        test_result.user = request.user
        test_result.test = selected_test
        test_result.correct_count = correct_answer_count
        test_result.incorrect_count = incorrect_answer_count
        test_result.save()

        # Формируем контекст
        context = {
            'correct_answer_count': correct_answer_count,
            'incorrect_answer_count': incorrect_answer_count,
            'incorrect_questions_list': incorrect_questions_list,
            'test_group_id': test_group_id,
            'test_id': test_id
        }

        # Переводим пользователя на страницу статистики
        return render(request, 'main/test_statistic.html', context)


# Страница аккаунта
@login_required(login_url=reverse_lazy('main:login'))
def account(request):
    return render(request, 'main/account.html', {})


# Страница статистики пользователя
@login_required(login_url=reverse_lazy('main:login'))
def statistic_page(request):
    # Список пройденных тестов и их результатов
    passed_tests = []

    # Во внешнем цикле перебираем все тесты
    for test in Test.objects.all().order_by('title'):
        results = TestResult.objects.filter(test=test, user=request.user).order_by('date_test')
        if not results.exists():
            continue

        # Во внутреннем цикле перебираем все результаты теста, полученного во внешнем цикле и добавляем их в список
        passed_tests.append({'test': test, 'result_test': []})
        for result in results:
            passed_tests[-1]['result_test'].append(result)

    context = {'passed_tests': passed_tests}
    return render(request, 'main/user_satistic.html', context)


# Контроллер страницы поиска
def find_page(request):
    if request.method == 'GET':
        return render(request, 'main/find_page.html', {})
    if request.method == 'POST':
        find_text = request.POST['find_text']
        find_text = find_text.strip().lower()
        if not find_text:
            return HttpResponseRedirect(reverse_lazy('main:find'))
        # Так как в sqlite, используемой в django, поиск без учета регистра не работает с кириллицей
        # придётся реализовать поиск самому, используя цикл для проверки отдельных элементов
        find_groups = []
        for group in TestGroup.objects.all():
            group_title = group.title.lower()
            if group_title.find(find_text) != (-1):
                find_groups.append(group)

        find_tests = []
        for test in Test.objects.all():
            test_title = test.title.lower()
            if test_title.find(find_text) != (-1):
                find_tests.append(test)

        context = {'find_text': find_text, 'groups': find_groups, 'tests': find_tests}
        return render(request, 'main/result_find_page.html', context)


# Контроллер для обслуживания программного интерфейса (пока оставлен пустым)
def api_controller(request):
    return HttpResponseRedirect(reverse_lazy('main:index'))


# Контроллер регистрации
def register_user(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            new_user = authenticate(request, username=request.POST['username'], password=request.POST['password1'])
            login(request, new_user)
            return HttpResponseRedirect(reverse_lazy('main:index'))

    if request.method == 'GET':
        form = UserRegisterForm()

    context = {'form': form}
    return render(request, 'main/register_user.html', context)


# Контроллер изменения данных пользователя
@login_required(login_url=reverse_lazy('main:login'))
def edit_account(request):
    if request.method == 'GET':
        form = UserEditForm(instance=request.user)
    if request.method == 'POST':
        user = request.user
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('main:account'))

    context = {'form': form}
    return render(request, 'main/edit_account_data.html', context)


# Контроллер входа
class LoginController(LoginView):
    template_name = 'main/login.html'


# Контроллер выхода
class LogoutController(LogoutView):
    next_page = reverse_lazy('main:index')


# Контроллер смены пароля
class PasswordChangeController(PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:account')

main/templates/main/account.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        <h3>{{ user.first_name }} {{ user.last_name }}</h3>
        Логин: {{ user }}<br>
        e-mail: {{ user.email }}
        <br>
        <p>
            <a href="{% url 'main:edit_account' %}">Изменить данные</a>
            &nbsp;-&nbsp;
            <a href="{% url 'main:change_password' %}">Сменить пароль</a>
        </p>
        <hr>
        <div class="block_with_margin">
            <a href="{% url 'main:index' %}">Вернуться на главную</a>
            <br>
            <a href="{% url 'main:statistic_page' %}">Моя статистика</a>
        </div>
    </div>
{% endblock %}

main/templates/main/edit_account_data.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        {% if user.is_authenticated %}
            {# Выводим форму #}
            <form method="post">
                {% csrf_token %}
                <table>
                    {% for element in form.visible_fields %}
                        <tr>
                            <td class="label_cell">
                                {{ element.label_tag }}
                            </td>
                            <td>
                                {{ element }}<br>
                                {% if element.errors %}
                                    <font color="red" size="2">
                                        {% for error in element.errors %}
                                            {{ error }}
                                            {% if not forloop.last %}<br>{% endif %}
                                        {% endfor %}
                                    </font>
                                    <br>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td></td>
                        <td>
                            <input type="submit" value="Сохранить изменения">
                        </td>
                    </tr>
                </table>
            </form>
        {% else %}
            Вам нужно выполнить вход или зарегистрироваться.
            <a href="{% url 'main:index' %}">Перейти на главную страницу</a>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/find_page.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        <form method="post">
            {% csrf_token %}
            <input type="text" name='find_text' size="35">
            <input type="submit" value="Найти">
        </form>
    </div>
{% endblock %}

main/templates/main/index.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        <p>
            Темы:
        </p>
        <hr>
        <ul>
            {% for test_group in test_groups %}
                <li><a href="{% url 'main:test_list' test_group_id=test_group.pk %}">{{ test_group }}</a></li>
            {% empty %}
                <div class="block_with_margin">
                    Извините, но на сайт пока не добавлены темы для тестирования...
                </div>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

main/templates/main/invalid_answer_count.html
{% extends 'layout/basic.html' %}

{%  block content %}
    <div class="basic_block">
        Вы ответили не на все вопросы. Тест не засчитан!
        <a href="{% url 'main:test_page' test_group_id=test_group_id test_id=test_id %}">
            Попробовать еще раз
        </a>
        или
        <a href="{% url 'main:index' %}">
            вернуться на главную
        </a>
    </div>
{%  endblock %}

main/templates/main/login.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        {% if not user.is_authenticated %}
            <form method="post">
                {% csrf_token %}
                <table>
                    {% for element in form.visible_fields %}
                        <tr>
                            <td>
                                {{ element.label_tag }}
                            </td>
                            <td>
                                {{ element }}
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td></td>
                        <td>
                            {% if not next %}
                                <input type="hidden" name="next" value="{% url 'main:index' %}">
                            {% endif %}
                            <input type="submit" value="Войти">
                        </td>
                    </tr>
                </table>
            </form>
        {% else %}
            Вы уже выполнили вход.
            <a href="{% url 'main:index' %}">Перейти на главную страницу</a>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/password_change.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        {% if user.is_authenticated %}
            {# Выводим форму #}
            <form method="post">
                {% csrf_token %}
                <table>
                    {% for element in form.visible_fields %}
                        <tr>
                            <td class="label_cell">
                                {{ element.label_tag }}
                            </td>
                            <td>
                                {{ element }}<br>
                                {% if element.errors %}
                                    <font color="red" size="2">
                                        {% for error in element.errors %}
                                            {{ error }}
                                            {% if not forloop.last %}<br>{% endif %}
                                        {% endfor %}
                                    </font>
                                    <br>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td></td>
                        <td>
                            <input type="submit" value="Сохранить изменения">
                        </td>
                    </tr>
                </table>
            </form>
        {% else %}
            Вам нужно выполнить вход или зарегистрироваться.
            <a href="{% url 'main:index' %}">Перейти на главную страницу</a>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/register_user.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        {% if not user.is_authenticated %}
            {# Выводим форму #}
            <form method="post">
                {% csrf_token %}
                <table>
                    {% for element in form.visible_fields %}
                        <tr>
                            <td class="label_cell">
                                {{ element.label_tag }}
                            </td>
                            <td>
                                {{ element }}<br>
                                {% if element.errors %}
                                    <font color="red" size="2">
                                        {% for error in element.errors %}
                                            {{ error }}
                                            {% if not forloop.last %}<br>{% endif %}
                                        {% endfor %}
                                    </font>
                                    <br>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td></td>
                        <td>
                            <input type="submit" value="Зарегистрироваться">
                        </td>
                    </tr>
                </table>
            </form>
        {% else %}
            Вы уже выполнили регистрацию.
            <a href="{% url 'main:index' %}">Перейти на главную страницу</a>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/result_find_page.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        {% if tests or groups %}
            Вы искали: {{ find_text }}
            <hr>

            {# Выводим список найденных групп #}
            {% if groups %}
                Группы:
                <ul>
                    {% for group in groups %}
                        <li>
                            <a href="{% url 'main:test_list' test_group_id=group.pk %}">
                                {{ group }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
                <br>
            {% endif %}

            {# Выводим список найденных тестов #}
            {% if tests %}
                Тесты:
                <ul>
                    {% for test in tests %}
                        <li>
                            <a href="{% url 'main:test_page' test_group_id=test.test_group.pk test_id=test.pk %}">
                                {{ test }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% else %}
            По вашему запросу ничего не найдено.
            <a href="{% url 'main:index' %}">Вернуться на главную страницу</a>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/test_list.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        <p>
            <a href="{% url 'main:index' %}" title="К выбору тем">{{ selected_group }}</a>
        </p>
        <hr>
        {% if tests %}
            <ul>
                {% for test in tests %}
                    <li>
                        <a href="{% url 'main:test_page' test_group_id=selected_group.pk test_id=test.pk %}">
                            {{ test }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <div class="block_with_margin">
                Извините, но тестов по данной теме на сайте нет...
            </div>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/test_not_found_page.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        Извините, но выбранный тест не доступен.
        <a href="{% url 'main:index' %}">Вернуться на главную страницу</a>
    </div>
{% endblock %}

main/templates/main/test_page.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        <p>
            <a href="{% url 'main:index' %}" title="К выбору тем">
                {{ selected_group }}
            </a>
            |
            <a href="{% url 'main:test_list' test_group_id=selected_group.pk %}" title="К выбору тестов">
                {{ selected_test }}
            </a>
        </p>
        <hr>
        {% if questions|length != 0 %}
            <div class="block_with_margin">
                <form method="post">
                    {% csrf_token %}
                    {% for question in questions %}
                        <p>
                            {{ question.title }}
                        </p>
                        <div class="block_with_margin">
                            {% for answer in question.answers %}
                                {% autoescape off %}
                                    {{ answer }}<br>
                                {% endautoescape %}
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <br>
                    <input type="submit" value="Готово!">
                </form>
            </div>
        {% else %}
            <div class="block_with_margin">
                Извините, но вопросов в данном тесте пока нет...
            </div>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/test_statistic.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        <a href="{% url 'main:test_page' test_group_id=test_group_id test_id=test_id %}">
            Пройти тест ещё раз
        </a>
        |
        <a href="{% url 'main:index' %}">
            Вернуться на главную
        </a>
        <hr>
        <div class="block_with_margin">
            {% if incorrect_answer_count == 0 %}
                Вы ответили правильно на все вопросы!
            {% endif %}
            {% if correct_answer_count == 0 %}
                Вы не ответили правильно ни на один вопрос!
            {% endif %}
            {% if correct_answer_count > 0 and incorrect_answer_count > 0 %}
                Правильных ответов: {{ correct_answer_count }}
                <br>
                Неправильных ответов: {{ incorrect_answer_count }}
                <p>
                    Вы ответили неправильно на следующие вопросы:
                <ul>
                    {% for incorrect_questions in incorrect_questions_list %}
                        <li>{{ incorrect_questions.title }}</li>
                    {% endfor %}
                </ul>
                </p>
            {% endif %}
        </div>
    </div>
{% endblock %}

main/templates/main/user_satistic.html
{% extends 'layout/basic.html' %}

{% block content %}
    <div class="basic_block">
        Ваши результаты |
        <a href="{% url 'main:index' %}">Вернуться на главную</a>
        <hr>
        {% if passed_tests %}
            <ul>
                {% for passed_test in passed_tests %}
                    <li>
                        <a href="{% url 'main:test_page' test_group_id=passed_test.test.test_group.pk test_id=passed_test.test.pk %}">
                            {{ passed_test.test }}
                        </a>
                    </li>
                    <ul>
                        {% for result in passed_test.result_test %}
                            <li>
                                {{ result.date_test }}<br>
                                Правильных ответов: {{ result.correct_count }} |
                                Неправильных ответов: {{ result.incorrect_count }}<br>
                            </li>
                        {% endfor %}
                    </ul>
                {% endfor %}
            </ul>
        {% else %}
            Вы не проходили ни одного теста.
        {% endif %}
    </div>
{% endblock %}